#pragma once

#include <filesystem>
#include <memory>
#include <optional>
#include <string>
#include <string_view>

namespace sonora::assets {

// One file served over the sonora:// scheme.
//
// `data` may point either at static storage compiled into the binary or at a
// buffer kept alive by `owner`. That split is what lets the shipping path serve
// the UI with zero copies while the development path can read from disk.
struct Asset {
  std::string_view data;
  std::string mime_type;
  std::shared_ptr<const std::string> owner;  // null when data is static
};

class AssetStore {
 public:
  virtual ~AssetStore() = default;

  AssetStore(const AssetStore&) = delete;
  AssetStore& operator=(const AssetStore&) = delete;

  // `path` is the URL path, always starting with '/'.
  [[nodiscard]] virtual std::optional<Asset> Lookup(std::string_view path) const = 0;

  // Human-readable description for logs and the 404 page.
  [[nodiscard]] virtual std::string Describe() const = 0;

 protected:
  AssetStore() = default;
};

// Serves the table generated by tools/embed_assets.py at build time.
std::unique_ptr<AssetStore> MakeEmbeddedAssetStore();

// Serves files from a directory. Used in development so a UI change is a
// reload instead of a C++ rebuild.
std::unique_ptr<AssetStore> MakeFilesystemAssetStore(std::filesystem::path root);

// Filesystem store when SONORA_UI_DIST_DIR is defined and exists (debug
// builds), embedded store otherwise.
std::unique_ptr<AssetStore> MakeDefaultAssetStore();

[[nodiscard]] std::string MimeTypeForPath(std::string_view path);

}  // namespace sonora::assets
