#!/usr/bin/env python3
"""Generate a C++ table of the built web UI so it ships inside the executable.

Why embed at all: the alternative is loading the UI from files next to the
binary, which means the interface can be swapped without touching the signed
executable. Embedding makes the UI part of what the code signature covers, and
removes a whole class of "works on my machine" from the installer.

Development builds do not use this table -- they read ui/dist directly so a UI
change is a reload instead of a C++ rebuild. See docs/adr/0003.

When the input directory does not exist the generator emits an empty table, so
a fresh checkout still links before anyone has run `npm run build`.

Usage:
    python tools/embed_assets.py --input ui/dist --output build/embedded_assets.cpp
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

MIME_TYPES = {
    ".html": "text/html",
    ".htm": "text/html",
    ".js": "text/javascript",
    ".mjs": "text/javascript",
    ".css": "text/css",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".webp": "image/webp",
    ".ico": "image/x-icon",
    ".woff": "font/woff",
    ".woff2": "font/woff2",
    ".map": "application/json",
    ".txt": "text/plain",
}

# Source maps are useful in a debug build and are dead weight (and a source
# leak) in a shipped one. They are never embedded.
SKIP_SUFFIXES = {".map"}

HEADER = """// Generated by tools/embed_assets.py -- do not edit, do not commit.
#include <sonora/assets/embedded_assets.h>

namespace sonora::assets::embedded {
namespace {
"""


def cpp_byte_array(name: str, data: bytes) -> str:
    lines = [f"const unsigned char {name}[] = {{"]
    for start in range(0, len(data), 16):
        chunk = data[start : start + 16]
        lines.append("    " + "".join(f"0x{b:02x}, " for b in chunk).rstrip())
    lines.append("};")
    # A zero-length array is ill-formed in C++; give empty files one byte.
    if not data:
        return f"const unsigned char {name}[1] = {{0x00}};"
    return "\n".join(lines)


def collect(root: Path) -> list[tuple[str, Path]]:
    if not root.is_dir():
        return []
    entries = []
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.suffix.lower() in SKIP_SUFFIXES:
            continue
        url_path = "/" + path.relative_to(root).as_posix()
        entries.append((url_path, path))
    return entries


def generate(root: Path, output: Path) -> int:
    entries = collect(root)

    parts = [HEADER]
    total = 0
    for index, (_, path) in enumerate(entries):
        data = path.read_bytes()
        total += len(data)
        parts.append(cpp_byte_array(f"kAsset{index}", data))
        parts.append("")

    parts.append("}  // namespace\n")
    parts.append("const Entry kEntries[] = {")
    if entries:
        for index, (url_path, path) in enumerate(entries):
            size = path.stat().st_size
            mime = MIME_TYPES.get(path.suffix.lower(), "application/octet-stream")
            parts.append(f'    {{"{url_path}", kAsset{index}, {size}, "{mime}"}},')
    else:
        # An empty array is ill-formed too; a sentinel keeps kEntryCount at 0.
        parts.append('    {"", nullptr, 0, ""},')
    parts.append("};")
    parts.append(f"const std::size_t kEntryCount = {len(entries)};")
    parts.append("\n}  // namespace sonora::assets::embedded")

    text = "\n".join(parts) + "\n"

    # Only rewrite when the content changed, so an unchanged UI does not force
    # a rebuild of everything that includes it.
    if output.exists() and output.read_text(encoding="utf-8") == text:
        print(f"embed_assets: unchanged ({len(entries)} files, {total / 1024:.1f} KiB)")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    print(f"embed_assets: {len(entries)} files, {total / 1024:.1f} KiB -> {output}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=Path, help="built UI directory")
    parser.add_argument("--output", required=True, type=Path, help="generated .cpp")
    args = parser.parse_args()
    return generate(args.input, args.output)


if __name__ == "__main__":
    sys.exit(main())
