#!/usr/bin/env python3
"""Generate the native<->web bridge from schema/bridge.schema.json.

Emits three files from one description:

  * a C++ header  -- shared structs, request/response types, the handler
                     interface, the typed event emitter, dispatch
  * a C++ source  -- JSON parsing, serialisation and the dispatch table
  * a TypeScript  -- the same shapes, plus typed call wrappers and typed
                     event subscription

The point is not to save typing. It is that the two ends cannot drift: adding a
method to the schema makes the C++ fail to compile until a handler exists, and
gives the TypeScript the new signature in the same build. A hand-written bridge
drifts the first time someone renames a field on one side only, and the failure
surfaces at runtime in a message nobody reads.

The same argument applies to events, which is why they are generated too rather
than being "just a string and some JSON": an event name that does not exist is
a compile error on the native side and a type error in the page.

Usage:
    python tools/gen_bridge.py --schema schema/bridge.schema.json \\
        --cpp-header build/generated/bridge_generated.h \\
        --cpp-source build/generated/bridge_generated.cpp \\
        --ts ui/src/bridge/generated.ts
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

SCALARS = {
    #  schema      C++                TypeScript
    "string": ("std::string", "string"),
    "int": ("std::int64_t", "number"),
    "double": ("double", "number"),
    "bool": ("bool", "boolean"),
}

NAME_RE = re.compile(r"^[a-z][A-Za-z0-9]*$")
TYPE_NAME_RE = re.compile(r"^[A-Z][A-Za-z0-9]*$")

BANNER = "// Generated by tools/gen_bridge.py from schema/bridge.schema.json.\n// Do not edit; edit the schema and rebuild.\n"


# ---------------------------------------------------------------------------
# Schema loading and validation
# ---------------------------------------------------------------------------


class SchemaError(Exception):
    pass


def pascal(name: str) -> str:
    return name[:1].upper() + name[1:]


class Field:
    def __init__(self, raw: dict, where: str, struct_names: set[str]):
        self.name = raw.get("name", "")
        if not NAME_RE.match(self.name):
            raise SchemaError(f"{where}: field name '{self.name}' must be lowerCamelCase")
        self.type = raw.get("type", "")
        self.is_struct = self.type in struct_names
        if not self.is_struct and self.type not in SCALARS:
            known = ", ".join(sorted(SCALARS) + sorted(struct_names))
            raise SchemaError(f"{where}.{self.name}: unknown type '{self.type}'; expected one of {known}")
        self.array = bool(raw.get("array", False))
        self.optional = bool(raw.get("optional", False))
        self.summary = raw.get("summary", "")
        if self.array and self.optional:
            # Allowed by the type system, but an absent list and an empty list
            # mean the same thing to every caller that has ever existed.
            raise SchemaError(f"{where}.{self.name}: use an empty array, not an optional array")
        if self.is_struct and self.optional:
            # Nothing needs it yet, and an optional struct doubles the parsing
            # paths. Left out until something actually asks for it.
            raise SchemaError(f"{where}.{self.name}: optional struct fields are not supported")

    @property
    def base_cpp(self) -> str:
        return self.type if self.is_struct else SCALARS[self.type][0]

    @property
    def cpp_type(self) -> str:
        if self.array:
            return f"std::vector<{self.base_cpp}>"
        if self.optional:
            return f"std::optional<{self.base_cpp}>"
        return self.base_cpp

    @property
    def ts_type(self) -> str:
        base = self.type if self.is_struct else SCALARS[self.type][1]
        return f"{base}[]" if self.array else base


class StructType:
    """A named record shared by several methods, declared under "types"."""

    def __init__(self, name: str, raw: dict, struct_names: set[str]):
        if not TYPE_NAME_RE.match(name):
            raise SchemaError(f"type '{name}' must be PascalCase")
        self.name = name
        self.summary = raw.get("summary", "")
        raw_fields = raw.get("fields", [])
        if not raw_fields:
            raise SchemaError(f"type '{name}' has no fields")
        # Structs hold scalars only. Nesting is a feature with no user yet, and
        # every level of it is another set of parse paths to get wrong.
        self.fields = [Field(f, f"types.{name}", set()) for f in raw_fields]
        _reject_duplicates(self.fields, f"type '{name}'")
        del struct_names


class Event:
    def __init__(self, raw: dict, capability: str, struct_names: set[str]):
        self.short_name = raw.get("name", "")
        where = f"{capability}.{self.short_name}"
        if not NAME_RE.match(self.short_name):
            raise SchemaError(f"{where}: event name must be lowerCamelCase")
        self.capability = capability
        self.wire_name = f"{capability}.{self.short_name}"
        self.summary = raw.get("summary", "")
        self.coalesce = bool(raw.get("coalesce", False))
        self.payload = [Field(f, f"{where}.payload", struct_names) for f in raw.get("payload", [])]
        _reject_duplicates(self.payload, where)

    @property
    def cpp_base(self) -> str:
        return pascal(self.capability) + pascal(self.short_name)


class Method:
    def __init__(self, raw: dict, capability: str, struct_names: set[str]):
        self.short_name = raw.get("name", "")
        where = f"{capability}.{self.short_name}"
        if not NAME_RE.match(self.short_name):
            raise SchemaError(f"{where}: method name must be lowerCamelCase")
        self.capability = capability
        self.wire_name = f"{capability}.{self.short_name}"
        self.summary = raw.get("summary", "")
        self.params = [Field(f, f"{where}.params", struct_names) for f in raw.get("params", [])]
        self.result = [Field(f, f"{where}.result", struct_names) for f in raw.get("result", [])]
        _reject_duplicates(self.params, where)
        _reject_duplicates(self.result, where)

    @property
    def cpp_base(self) -> str:
        return pascal(self.capability) + pascal(self.short_name)


def _reject_duplicates(fields: list[Field], where: str) -> None:
    seen: set[str] = set()
    for field in fields:
        if field.name in seen:
            raise SchemaError(f"{where}: duplicate field '{field.name}'")
        seen.add(field.name)


class Capability:
    def __init__(self, raw: dict, struct_names: set[str]):
        self.name = raw.get("name", "")
        if not NAME_RE.match(self.name):
            raise SchemaError(f"capability name '{self.name}' must be lowerCamelCase")
        self.version = raw.get("version")
        if not isinstance(self.version, int) or self.version < 1:
            raise SchemaError(f"{self.name}: version must be an integer >= 1")
        self.required = bool(raw.get("required", False))
        self.summary = raw.get("summary", "")
        self.methods = [Method(m, self.name, struct_names) for m in raw.get("methods", [])]
        self.events = [Event(e, self.name, struct_names) for e in raw.get("events", [])]


class Schema:
    def __init__(self, raw: dict):
        self.protocol_version = raw.get("protocolVersion")
        if not isinstance(self.protocol_version, int):
            raise SchemaError("protocolVersion must be an integer")

        raw_types = raw.get("types", {})
        if not isinstance(raw_types, dict):
            raise SchemaError('"types" must be an object mapping a name to its fields')
        names = set(raw_types)
        self.types = [StructType(name, raw_types[name], names) for name in sorted(names)]

        self.capabilities = [Capability(c, names) for c in raw.get("capabilities", [])]
        if not self.capabilities:
            raise SchemaError("the schema defines no capabilities")
        if not any(cap.required for cap in self.capabilities):
            # Negotiation has to start somewhere. If every capability can be
            # switched off, so can the one that reports which are on.
            raise SchemaError("at least one capability must be marked \"required\"")

        seen_caps: set[str] = set()
        seen_names: set[str] = set()
        for cap in self.capabilities:
            if cap.name in seen_caps:
                raise SchemaError(f"duplicate capability '{cap.name}'")
            seen_caps.add(cap.name)
            for item in [*cap.methods, *cap.events]:
                if item.wire_name in seen_names:
                    raise SchemaError(f"duplicate method or event '{item.wire_name}'")
                seen_names.add(item.wire_name)

    @property
    def methods(self) -> list[Method]:
        return [m for cap in self.capabilities for m in cap.methods]

    @property
    def events(self) -> list[Event]:
        return [e for cap in self.capabilities for e in cap.events]


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------


def doc(text: str, indent: str = "") -> list[str]:
    return [f"{indent}// {line}" for line in _wrap(text, 76 - len(indent))] if text else []


def _wrap(text: str, width: int) -> list[str]:
    words, lines, current = text.split(), [], ""
    for word in words:
        if current and len(current) + 1 + len(word) > width:
            lines.append(current)
            current = word
        else:
            current = f"{current} {word}".strip()
    if current:
        lines.append(current)
    return lines


def cpp_bool(value: bool) -> str:
    return "true" if value else "false"


# ---------------------------------------------------------------------------
# C++ header
# ---------------------------------------------------------------------------


def emit_struct_decl(name: str, fields: list[Field], *, parse: bool, serialise: bool) -> list[str]:
    out = [f"struct {name} {{"]
    for field in fields:
        out += doc(field.summary, "  ")
        out.append(f"  {field.cpp_type} {field.name}{{}};")
    if fields:
        out.append("")
    if parse:
        out.append(f"  [[nodiscard]] static {name} FromJson(const nlohmann::json& value);")
    if serialise:
        out.append("  [[nodiscard]] nlohmann::json ToJson() const;")
    out += ["};", ""]
    return out


def emit_cpp_header(schema: Schema) -> str:
    out = [BANNER, "#pragma once", ""]
    out += [
        "#include <cstdint>",
        "#include <optional>",
        "#include <string>",
        "#include <string_view>",
        "#include <vector>",
        "",
        "#include <nlohmann/json.hpp>",
        "",
        "#include <sonora/bridge/capabilities.h>",
        "#include <sonora/bridge/protocol.h>",
        "",
        "namespace sonora::bridge {",
        "",
        f"inline constexpr int kProtocolVersion = {schema.protocol_version};",
        "",
    ]

    out += [
        "// Every capability this build knows about, in schema order. Generated so",
        "// that shell.getCapabilities cannot fall out of step with what is actually",
        "// implemented, and so that a required capability is required by",
        "// construction rather than by a runtime check someone can forget.",
        "inline constexpr CapabilityInfo kCapabilities[] = {",
    ]
    for cap in schema.capabilities:
        out.append(f'    {{"{cap.name}", {cap.version}, {cpp_bool(cap.required)}}},')
    out += ["};", ""]

    if schema.types:
        out += ["// Shared record types, declared once under \"types\" in the schema.", ""]
        for struct in schema.types:
            out += doc(f"{struct.name}: {struct.summary}")
            out += emit_struct_decl(struct.name, struct.fields, parse=True, serialise=True)

    for method in schema.methods:
        out += doc(f"{method.wire_name}: {method.summary}")
        out += emit_struct_decl(
            method.cpp_base + "Params", method.params, parse=True, serialise=False
        )
        out += emit_struct_decl(
            method.cpp_base + "Result", method.result, parse=False, serialise=True
        )

    for event in schema.events:
        out += doc(f"{event.wire_name} (event): {event.summary}")
        out += emit_struct_decl(
            event.cpp_base + "Event", event.payload, parse=False, serialise=True
        )

    out += [
        "// Implemented by the application. Pure virtual on purpose: a method added",
        "// to the schema stops the build here until someone handles it, which is a",
        "// better reminder than a runtime 'unknown method' nobody sees.",
        "//",
        "// A handler signals failure by throwing BridgeError. Dispatch catches it",
        "// and turns it into a typed response; nothing escapes into CEF.",
        "class BridgeHandlers {",
        " public:",
        "  virtual ~BridgeHandlers() = default;",
        "",
    ]
    for method in schema.methods:
        out += doc(f"{method.wire_name}", "  ")
        out.append(
            f"  virtual {method.cpp_base}Result {method.cpp_base}("
            f"const {method.cpp_base}Params& params) = 0;"
        )
        out.append("")
    out += [" protected:", "  BridgeHandlers() = default;", "};", ""]

    if schema.events:
        out += [
            "// The transport for events, implemented by the shell. Takes a name and a",
            "// payload because that is all a transport can know; nobody calls it",
            "// directly -- Events below is the door.",
            "class EventSink {",
            " public:",
            "  virtual ~EventSink() = default;",
            "",
            "  // coalesce: a pending event of the same name may be replaced by this",
            "  // one instead of both being delivered.",
            "  virtual void Emit(std::string_view name,",
            "                    const nlohmann::json& payload,",
            "                    bool coalesce) = 0;",
            "",
            " protected:",
            "  EventSink() = default;",
            "};",
            "",
            "// One method per event in the schema, so an event name is never spelled",
            "// out at a call site and cannot be typed wrong. Whether an event",
            "// coalesces is a property of the event, decided in the schema, not an",
            "// argument the caller passes differently from one place to the next.",
            "class Events {",
            " public:",
            "  explicit Events(EventSink& sink) : sink_(&sink) {}",
            "",
        ]
        for event in schema.events:
            out += doc(f"{event.wire_name}", "  ")
            out.append(
                f"  void {event.cpp_base}(const {event.cpp_base}Event& payload) const {{"
            )
            out.append(
                f'    sink_->Emit("{event.wire_name}", payload.ToJson(), '
                f"/*coalesce=*/{cpp_bool(event.coalesce)});"
            )
            out += ["  }", ""]
        out += [" private:", "  EventSink* sink_;", "};", ""]

    out += [
        "// Parses a request envelope, checks the capability is enabled, runs the",
        "// matching handler and serialises the answer. Never throws: every failure",
        "// comes back as a Response carrying an error code, because the caller is a",
        "// CEF callback that cannot handle one.",
        "[[nodiscard]] Response Dispatch(BridgeHandlers& handlers,",
        "                                const CapabilityRegistry& capabilities,",
        "                                std::string_view request_json);",
        "",
        "}  // namespace sonora::bridge",
        "",
    ]
    return "\n".join(out)


# ---------------------------------------------------------------------------
# C++ source
# ---------------------------------------------------------------------------


def emit_read(field: Field, indent: str = "  ") -> list[str]:
    """One field, read out of `value` into `out`."""
    quoted = f'"{field.name}"'
    if field.is_struct:
        reader = f"ReadStructArray<{field.type}>" if field.array else f"ReadStruct<{field.type}>"
    elif field.array:
        reader = f"ReadArray<{field.base_cpp}>"
    else:
        reader = f"ReadScalar<{field.base_cpp}>"
    call = f"{reader}(value.at({quoted}), {quoted})"

    if field.array:
        # An absent list is an empty list. Callers that care about the
        # difference should not be using an array.
        return [
            f"{indent}if (value.contains({quoted})) {{",
            f"{indent}  out.{field.name} = {call};",
            f"{indent}}}",
        ]
    if field.optional:
        return [
            f"{indent}if (value.contains({quoted}) && !value.at({quoted}).is_null()) {{",
            f"{indent}  out.{field.name} = {call};",
            f"{indent}}}",
        ]
    return [
        f"{indent}if (!value.contains({quoted})) {{",
        f"{indent}  throw BridgeError(ErrorCode::kInvalidParams,",
        f"{indent}                    \"missing required field '{field.name}'\");",
        f"{indent}}}",
        f"{indent}out.{field.name} = {call};",
    ]


def emit_write(field: Field, indent: str = "  ") -> list[str]:
    quoted = f'"{field.name}"'
    if field.is_struct and field.array:
        return [
            f"{indent}{{",
            f"{indent}  nlohmann::json items = nlohmann::json::array();",
            f"{indent}  for (const auto& item : {field.name}) {{",
            f"{indent}    items.push_back(item.ToJson());",
            f"{indent}  }}",
            f"{indent}  out[{quoted}] = std::move(items);",
            f"{indent}}}",
        ]
    if field.is_struct:
        return [f"{indent}out[{quoted}] = {field.name}.ToJson();"]
    if field.optional:
        return [
            f"{indent}if ({field.name}.has_value()) {{",
            f"{indent}  out[{quoted}] = *{field.name};",
            f"{indent}}}",
        ]
    return [f"{indent}out[{quoted}] = {field.name};"]


def emit_from_json(name: str, fields: list[Field], *, object_check: str) -> list[str]:
    out = [f"{name} {name}::FromJson(const nlohmann::json& value) {{"]
    if fields:
        out += [
            "  if (!value.is_object()) {",
            f'    throw BridgeError(ErrorCode::kInvalidParams, "{object_check}");',
            "  }",
        ]
    out.append(f"  {name} out;")
    for field in fields:
        out += emit_read(field)
    if not fields:
        out.append("  (void)value;  // nothing to read")
    out += ["  return out;", "}", ""]
    return out


def emit_to_json(name: str, fields: list[Field]) -> list[str]:
    out = [
        f"nlohmann::json {name}::ToJson() const {{",
        "  nlohmann::json out = nlohmann::json::object();",
    ]
    for field in fields:
        out += emit_write(field)
    out += ["  return out;", "}", ""]
    return out


def emit_cpp_source(schema: Schema, header_name: str) -> str:
    out = [BANNER, f'#include "{header_name}"', "", "namespace sonora::bridge {", ""]

    for struct in schema.types:
        out += emit_from_json(
            struct.name, struct.fields, object_check=f"{struct.name} must be an object"
        )
        out += emit_to_json(struct.name, struct.fields)

    for method in schema.methods:
        out += emit_from_json(
            method.cpp_base + "Params", method.params, object_check="params must be an object"
        )
        out += emit_to_json(method.cpp_base + "Result", method.result)

    for event in schema.events:
        out += emit_to_json(event.cpp_base + "Event", event.payload)

    out += [
        "Response Dispatch(BridgeHandlers& handlers,",
        "                  const CapabilityRegistry& capabilities,",
        "                  std::string_view request_json) {",
        "  std::string method;",
        "  try {",
        "    const Request request = Request::Parse(request_json);",
        "    method = request.method;",
        "",
    ]
    first = True
    for method in schema.methods:
        keyword = "if" if first else "} else if"
        first = False
        out.append(f'    {keyword} (request.method == "{method.wire_name}") {{')
        out.append(f'      capabilities.Require("{method.capability}");')
        out.append(f"      const auto params = {method.cpp_base}Params::FromJson(request.params);")
        out.append(f"      return Response::Ok(handlers.{method.cpp_base}(params).ToJson());")
    out += [
        "    } else {",
        "      throw BridgeError(ErrorCode::kUnknownMethod,",
        '                        "no such method: " + request.method);',
        "    }",
        "  } catch (const BridgeError& error) {",
        "    return Response::Failed(error.code(), error.what(), method);",
        "  } catch (const nlohmann::json::exception& error) {",
        "    return Response::Failed(ErrorCode::kInvalidParams, error.what(), method);",
        "  } catch (const std::exception& error) {",
        "    // A handler threw something of its own. The bridge must not take the",
        "    // process down over it, but it is a bug, not a protocol error.",
        "    return Response::Failed(ErrorCode::kInternalError, error.what(), method);",
        "  }",
        "}",
        "",
        "}  // namespace sonora::bridge",
        "",
    ]
    return "\n".join(out)


# ---------------------------------------------------------------------------
# TypeScript
# ---------------------------------------------------------------------------


def ts_doc(text: str, indent: str = "") -> list[str]:
    if not text:
        return []
    lines = _wrap(text, 72 - len(indent))
    if len(lines) == 1:
        return [f"{indent}/** {lines[0]} */"]
    return [f"{indent}/**"] + [f"{indent} * {line}" for line in lines] + [f"{indent} */"]


def emit_ts_interface(name: str, fields: list[Field], summary: str = "") -> list[str]:
    out = ts_doc(summary)
    if not fields:
        return out + [f"export type {name} = Record<string, never>;", ""]
    out.append(f"export interface {name} {{")
    for field in fields:
        out += ts_doc(field.summary, "  ")
        optional = "?" if field.optional else ""
        out.append(f"  readonly {field.name}{optional}: {field.ts_type};")
    out += ["}", ""]
    return out


def emit_ts(schema: Schema) -> str:
    out = [
        BANNER.rstrip(),
        "",
        f"export const PROTOCOL_VERSION = {schema.protocol_version};",
        "",
    ]

    for struct in schema.types:
        out += emit_ts_interface(struct.name, struct.fields, struct.summary)

    out += [
        "/** A capability as the schema declares it, known at build time. */",
        "export interface DeclaredCapability {",
        "  readonly name: string;",
        "  readonly version: number;",
        "  readonly required: boolean;",
        "}",
        "",
        "/** What this build of the UI was compiled against. */",
        "export const DECLARED_CAPABILITIES: readonly DeclaredCapability[] = [",
    ]
    for cap in schema.capabilities:
        out.append(
            f"  {{ name: '{cap.name}', version: {cap.version}, "
            f"required: {str(cap.required).lower()} }},"
        )
    out += ["];", ""]

    for method in schema.methods:
        out += ts_doc(f"{method.wire_name}: {method.summary}")
        out += emit_ts_interface(method.cpp_base + "Params", method.params)
        out += emit_ts_interface(method.cpp_base + "Result", method.result)

    out.append("export interface MethodSignatures {")
    for method in schema.methods:
        out.append(
            f"  '{method.wire_name}': {{ params: {method.cpp_base}Params; "
            f"result: {method.cpp_base}Result }};"
        )
    out += ["}", ""]

    out += [
        "export type MethodName = keyof MethodSignatures;",
        "",
        "export const METHOD_NAMES: readonly MethodName[] = [",
    ]
    for method in schema.methods:
        out.append(f"  '{method.wire_name}',")
    out += ["];", ""]

    for event in schema.events:
        out += ts_doc(f"{event.wire_name}: {event.summary}")
        out += emit_ts_interface(event.cpp_base + "Event", event.payload)

    out.append("export interface EventPayloads {")
    for event in schema.events:
        out.append(f"  '{event.wire_name}': {event.cpp_base}Event;")
    if not schema.events:
        out.append("  [never: string]: never;")
    out += ["}", ""]

    out += ["export type EventName = keyof EventPayloads;", "", "export const EVENT_NAMES: readonly EventName[] = ["]
    for event in schema.events:
        out.append(f"  '{event.wire_name}',")
    out += ["];", ""]

    out += [
        "/** The transport. Supplied by invoke.ts so this file stays pure types. */",
        "export type InvokeFn = <M extends MethodName>(",
        "  method: M,",
        "  params: MethodSignatures[M]['params'],",
        ") => Promise<MethodSignatures[M]['result']>;",
        "",
        "/** Builds the typed API surface over a transport. */",
        "export function createApi(invoke: InvokeFn) {",
        "  return {",
    ]
    for cap in schema.capabilities:
        out.append(f"    {cap.name}: {{")
        for method in cap.methods:
            if method.params:
                out.append(f"      {method.short_name}: (params: {method.cpp_base}Params) =>")
                out.append(f"        invoke('{method.wire_name}', params),")
            else:
                out.append(f"      {method.short_name}: () =>")
                out.append(f"        invoke('{method.wire_name}', {{}}),")
        out.append("    },")
    out += ["  };", "}", "", "export type SonoraApi = ReturnType<typeof createApi>;", ""]
    return "\n".join(out)


# ---------------------------------------------------------------------------


def write_if_changed(path: Path, text: str, label: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == text:
        print(f"gen_bridge: {label} unchanged")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"gen_bridge: wrote {label} -> {path}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", required=True, type=Path)
    parser.add_argument("--cpp-header", type=Path)
    parser.add_argument("--cpp-source", type=Path)
    parser.add_argument("--ts", type=Path)
    args = parser.parse_args()

    try:
        raw = json.loads(args.schema.read_text(encoding="utf-8"))
        schema = Schema(raw)
    except json.JSONDecodeError as error:
        print(f"gen_bridge: {args.schema} is not valid JSON: {error}", file=sys.stderr)
        return 1
    except SchemaError as error:
        print(f"gen_bridge: invalid schema: {error}", file=sys.stderr)
        return 1

    if args.cpp_source and not args.cpp_header:
        print("gen_bridge: --cpp-source needs --cpp-header for the include", file=sys.stderr)
        return 1

    if args.cpp_header:
        write_if_changed(args.cpp_header, emit_cpp_header(schema), "C++ header")
    if args.cpp_source:
        write_if_changed(args.cpp_source, emit_cpp_source(schema, args.cpp_header.name), "C++ source")
    if args.ts:
        write_if_changed(args.ts, emit_ts(schema), "TypeScript")

    print(
        f"gen_bridge: {len(schema.methods)} method(s) and {len(schema.events)} event(s) "
        f"across {len(schema.capabilities)} capability(ies), "
        f"{len(schema.types)} shared type(s)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
