#!/usr/bin/env python3
"""Generate the native<->web bridge from schema/bridge.schema.json.

Emits three files from one description:

  * a C++ header  -- request/response structs, the handler interface, dispatch
  * a C++ source  -- JSON parsing, serialisation and the dispatch table
  * a TypeScript  -- the same shapes, plus typed call wrappers

The point is not to save typing. It is that the two ends cannot drift: adding a
method to the schema makes the C++ fail to compile until a handler exists, and
gives the TypeScript the new signature in the same build. A hand-written bridge
drifts the first time someone renames a field on one side only, and the failure
surfaces at runtime in a message nobody reads.

Usage:
    python tools/gen_bridge.py --schema schema/bridge.schema.json \\
        --cpp-header build/generated/bridge_generated.h \\
        --cpp-source build/generated/bridge_generated.cpp \\
        --ts ui/src/bridge/generated.ts
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

SCALARS = {
    #  schema      C++                TypeScript
    "string": ("std::string", "string"),
    "int": ("std::int64_t", "number"),
    "double": ("double", "number"),
    "bool": ("bool", "boolean"),
}

NAME_RE = re.compile(r"^[a-z][A-Za-z0-9]*$")

BANNER = "// Generated by tools/gen_bridge.py from schema/bridge.schema.json.\n// Do not edit; edit the schema and rebuild.\n"


# ---------------------------------------------------------------------------
# Schema loading and validation
# ---------------------------------------------------------------------------


class SchemaError(Exception):
    pass


def pascal(name: str) -> str:
    return name[:1].upper() + name[1:]


class Field:
    def __init__(self, raw: dict, where: str):
        self.name = raw.get("name", "")
        if not NAME_RE.match(self.name):
            raise SchemaError(f"{where}: field name '{self.name}' must be lowerCamelCase")
        self.type = raw.get("type", "")
        if self.type not in SCALARS:
            raise SchemaError(
                f"{where}.{self.name}: unknown type '{self.type}'; "
                f"expected one of {', '.join(sorted(SCALARS))}"
            )
        self.array = bool(raw.get("array", False))
        self.optional = bool(raw.get("optional", False))
        self.summary = raw.get("summary", "")
        if self.array and self.optional:
            # Allowed by the type system, but an absent list and an empty list
            # mean the same thing to every caller that has ever existed.
            raise SchemaError(f"{where}.{self.name}: use an empty array, not an optional array")

    @property
    def cpp_type(self) -> str:
        base = SCALARS[self.type][0]
        if self.array:
            return f"std::vector<{base}>"
        if self.optional:
            return f"std::optional<{base}>"
        return base

    @property
    def cpp_scalar(self) -> str:
        return SCALARS[self.type][0]

    @property
    def ts_type(self) -> str:
        base = SCALARS[self.type][1]
        return f"{base}[]" if self.array else base


class Method:
    def __init__(self, raw: dict, capability: str):
        self.short_name = raw.get("name", "")
        where = f"{capability}.{self.short_name}"
        if not NAME_RE.match(self.short_name):
            raise SchemaError(f"{where}: method name must be lowerCamelCase")
        self.capability = capability
        self.wire_name = f"{capability}.{self.short_name}"
        self.summary = raw.get("summary", "")
        self.params = [Field(f, f"{where}.params") for f in raw.get("params", [])]
        self.result = [Field(f, f"{where}.result") for f in raw.get("result", [])]
        for group in (self.params, self.result):
            seen = set()
            for field in group:
                if field.name in seen:
                    raise SchemaError(f"{where}: duplicate field '{field.name}'")
                seen.add(field.name)

    @property
    def cpp_base(self) -> str:
        return pascal(self.capability) + pascal(self.short_name)


class Capability:
    def __init__(self, raw: dict):
        self.name = raw.get("name", "")
        if not NAME_RE.match(self.name):
            raise SchemaError(f"capability name '{self.name}' must be lowerCamelCase")
        self.version = raw.get("version")
        if not isinstance(self.version, int) or self.version < 1:
            raise SchemaError(f"{self.name}: version must be an integer >= 1")
        self.summary = raw.get("summary", "")
        self.methods = [Method(m, self.name) for m in raw.get("methods", [])]


class Schema:
    def __init__(self, raw: dict):
        self.protocol_version = raw.get("protocolVersion")
        if not isinstance(self.protocol_version, int):
            raise SchemaError("protocolVersion must be an integer")
        self.capabilities = [Capability(c) for c in raw.get("capabilities", [])]
        if not self.capabilities:
            raise SchemaError("the schema defines no capabilities")

        seen_caps, seen_methods = set(), set()
        for cap in self.capabilities:
            if cap.name in seen_caps:
                raise SchemaError(f"duplicate capability '{cap.name}'")
            seen_caps.add(cap.name)
            for method in cap.methods:
                if method.wire_name in seen_methods:
                    raise SchemaError(f"duplicate method '{method.wire_name}'")
                seen_methods.add(method.wire_name)

    @property
    def methods(self) -> list[Method]:
        return [m for cap in self.capabilities for m in cap.methods]


# ---------------------------------------------------------------------------
# C++ header
# ---------------------------------------------------------------------------


def doc(text: str, indent: str = "") -> list[str]:
    return [f"{indent}// {line}" for line in _wrap(text, 76 - len(indent))] if text else []


def _wrap(text: str, width: int) -> list[str]:
    words, lines, current = text.split(), [], ""
    for word in words:
        if current and len(current) + 1 + len(word) > width:
            lines.append(current)
            current = word
        else:
            current = f"{current} {word}".strip()
    if current:
        lines.append(current)
    return lines


def emit_cpp_header(schema: Schema) -> str:
    out = [BANNER, "#pragma once", ""]
    out += [
        "#include <cstdint>",
        "#include <optional>",
        "#include <string>",
        "#include <vector>",
        "",
        "#include <nlohmann/json.hpp>",
        "",
        "#include <sonora/bridge/protocol.h>",
        "",
        "namespace sonora::bridge {",
        "",
        f"inline constexpr int kProtocolVersion = {schema.protocol_version};",
        "",
    ]

    out += [
        "// Every capability this build exposes, in schema order. Generated so that",
        "// shell.listCapabilities cannot fall out of step with what is implemented.",
        "struct CapabilityInfo {",
        "  const char* name;",
        "  int version;",
        "};",
        "inline constexpr CapabilityInfo kCapabilities[] = {",
    ]
    for cap in schema.capabilities:
        out.append(f'    {{"{cap.name}", {cap.version}}},')
    out += ["};", ""]

    for method in schema.methods:
        out += doc(f"{method.wire_name}: {method.summary}")
        for suffix, fields, needs_parse in (
            ("Params", method.params, True),
            ("Result", method.result, False),
        ):
            name = method.cpp_base + suffix
            out.append(f"struct {name} {{")
            for field in fields:
                out += doc(field.summary, "  ")
                out.append(f"  {field.cpp_type} {field.name}{{}};")
            if needs_parse:
                out.append("")
                out.append(f"  static {name} FromJson(const nlohmann::json& value);")
            else:
                out.append("")
                out.append("  [[nodiscard]] nlohmann::json ToJson() const;")
            out += ["};", ""]

    out += [
        "// Implemented by the application. Pure virtual on purpose: a method added",
        "// to the schema stops the build here until someone handles it, which is a",
        "// better reminder than a runtime 'unknown method' nobody sees.",
        "//",
        "// A handler signals failure by throwing BridgeError. Dispatch catches it",
        "// and turns it into a typed response; nothing escapes into CEF.",
        "class BridgeHandlers {",
        " public:",
        "  virtual ~BridgeHandlers() = default;",
        "",
    ]
    for method in schema.methods:
        out += doc(f"{method.wire_name}", "  ")
        out.append(
            f"  virtual {method.cpp_base}Result {method.cpp_base}("
            f"const {method.cpp_base}Params& params) = 0;"
        )
        out.append("")
    out += [" protected:", "  BridgeHandlers() = default;", "};", ""]

    out += [
        "// Parses a request envelope, runs the matching handler and serialises the",
        "// answer. Never throws: every failure comes back as a Response carrying an",
        "// error code, because the caller is a CEF callback that cannot handle one.",
        "[[nodiscard]] Response Dispatch(BridgeHandlers& handlers, std::string_view request_json);",
        "",
        "}  // namespace sonora::bridge",
        "",
    ]
    return "\n".join(out)


# ---------------------------------------------------------------------------
# C++ source
# ---------------------------------------------------------------------------


def emit_field_read(field: Field) -> list[str]:
    lines = []
    quoted = f'"{field.name}"'
    if field.array:
        lines.append(f"  if (value.contains({quoted})) {{")
        lines.append(
            f"    out.{field.name} = ReadArray<{field.cpp_scalar}>(value.at({quoted}), {quoted});"
        )
        lines.append("  }")
    elif field.optional:
        lines.append(f"  if (value.contains({quoted}) && !value.at({quoted}).is_null()) {{")
        lines.append(
            f"    out.{field.name} = ReadScalar<{field.cpp_scalar}>(value.at({quoted}), {quoted});"
        )
        lines.append("  }")
    else:
        lines.append(f"  if (!value.contains({quoted})) {{")
        lines.append(
            f"    throw BridgeError(ErrorCode::kInvalidParams, "
            f'"missing required field \'{field.name}\'");'
        )
        lines.append("  }")
        lines.append(
            f"  out.{field.name} = ReadScalar<{field.cpp_scalar}>(value.at({quoted}), {quoted});"
        )
    return lines


def emit_cpp_source(schema: Schema, header_name: str) -> str:
    out = [BANNER, f'#include "{header_name}"', "", "namespace sonora::bridge {", ""]

    for method in schema.methods:
        params_name = method.cpp_base + "Params"
        out.append(f"{params_name} {params_name}::FromJson(const nlohmann::json& value) {{")
        if method.params:
            out.append("  if (!value.is_object()) {")
            out.append(
                '    throw BridgeError(ErrorCode::kInvalidParams, "params must be an object");'
            )
            out.append("  }")
        out.append(f"  {params_name} out;")
        for field in method.params:
            out += emit_field_read(field)
        if not method.params:
            out.append("  (void)value;  // this method takes no parameters")
        out += ["  return out;", "}", ""]

        result_name = method.cpp_base + "Result"
        out.append(f"nlohmann::json {result_name}::ToJson() const {{")
        out.append("  nlohmann::json out = nlohmann::json::object();")
        for field in method.result:
            if field.optional:
                out.append(f"  if ({field.name}.has_value()) {{")
                out.append(f'    out["{field.name}"] = *{field.name};')
                out.append("  }")
            else:
                out.append(f'  out["{field.name}"] = {field.name};')
        out += ["  return out;", "}", ""]

    out += [
        "Response Dispatch(BridgeHandlers& handlers, std::string_view request_json) {",
        "  std::string method;",
        "  try {",
        "    const Request request = Request::Parse(request_json);",
        "    method = request.method;",
        "",
    ]
    first = True
    for method in schema.methods:
        keyword = "if" if first else "} else if"
        first = False
        out.append(f'    {keyword} (request.method == "{method.wire_name}") {{')
        out.append(
            f"      const auto params = {method.cpp_base}Params::FromJson(request.params);"
        )
        out.append(f"      return Response::Ok(handlers.{method.cpp_base}(params).ToJson());")
    out += [
        "    } else {",
        "      throw BridgeError(ErrorCode::kUnknownMethod,",
        '                        "no such method: " + request.method);',
        "    }",
        "  } catch (const BridgeError& error) {",
        "    return Response::Failed(error.code(), error.what(), method);",
        "  } catch (const nlohmann::json::exception& error) {",
        "    return Response::Failed(ErrorCode::kInvalidParams, error.what(), method);",
        "  } catch (const std::exception& error) {",
        "    // A handler threw something of its own. The bridge must not take the",
        "    // process down over it, but it is a bug, not a protocol error.",
        "    return Response::Failed(ErrorCode::kInternalError, error.what(), method);",
        "  }",
        "}",
        "",
        "}  // namespace sonora::bridge",
        "",
    ]
    return "\n".join(out)


# ---------------------------------------------------------------------------
# TypeScript
# ---------------------------------------------------------------------------


def ts_doc(text: str, indent: str = "") -> list[str]:
    if not text:
        return []
    lines = _wrap(text, 72 - len(indent))
    if len(lines) == 1:
        return [f"{indent}/** {lines[0]} */"]
    return [f"{indent}/**"] + [f"{indent} * {line}" for line in lines] + [f"{indent} */"]


def emit_ts(schema: Schema) -> str:
    out = [
        BANNER.replace("//", "//").rstrip(),
        "",
        f"export const PROTOCOL_VERSION = {schema.protocol_version};",
        "",
        "export interface CapabilityInfo {",
        "  readonly name: string;",
        "  readonly version: number;",
        "}",
        "",
        "export const CAPABILITIES: readonly CapabilityInfo[] = [",
    ]
    for cap in schema.capabilities:
        out.append(f"  {{ name: '{cap.name}', version: {cap.version} }},")
    out += ["] as const;", ""]

    for method in schema.methods:
        out += ts_doc(f"{method.wire_name}: {method.summary}")
        for suffix, fields in (("Params", method.params), ("Result", method.result)):
            name = method.cpp_base + suffix
            if not fields:
                out.append(f"export type {name} = Record<string, never>;")
                out.append("")
                continue
            out.append(f"export interface {name} {{")
            for field in fields:
                out += ts_doc(field.summary, "  ")
                optional = "?" if field.optional else ""
                out.append(f"  {field.name}{optional}: {field.ts_type};")
            out += ["}", ""]

    out.append("export interface MethodSignatures {")
    for method in schema.methods:
        out.append(
            f"  '{method.wire_name}': {{ params: {method.cpp_base}Params; "
            f"result: {method.cpp_base}Result }};"
        )
    out += ["}", ""]

    out += [
        "export type MethodName = keyof MethodSignatures;",
        "",
        "export const METHOD_NAMES: readonly MethodName[] = [",
    ]
    for method in schema.methods:
        out.append(f"  '{method.wire_name}',")
    out += ["];", ""]

    out += [
        "/** The transport. Supplied by invoke.ts so this file stays pure types. */",
        "export type InvokeFn = <M extends MethodName>(",
        "  method: M,",
        "  params: MethodSignatures[M]['params'],",
        ") => Promise<MethodSignatures[M]['result']>;",
        "",
        "/** Builds the typed API surface over a transport. */",
        "export function createApi(invoke: InvokeFn) {",
        "  return {",
    ]
    for cap in schema.capabilities:
        out.append(f"    {cap.name}: {{")
        for method in cap.methods:
            if method.params:
                out.append(
                    f"      {method.short_name}: (params: {method.cpp_base}Params) =>"
                )
                out.append(f"        invoke('{method.wire_name}', params),")
            else:
                out.append(f"      {method.short_name}: () =>")
                out.append(f"        invoke('{method.wire_name}', {{}}),")
        out.append("    },")
    out += ["  };", "}", "", "export type SonoraApi = ReturnType<typeof createApi>;", ""]
    return "\n".join(out)


# ---------------------------------------------------------------------------


def write_if_changed(path: Path, text: str, label: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == text:
        print(f"gen_bridge: {label} unchanged")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"gen_bridge: wrote {label} -> {path}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema", required=True, type=Path)
    parser.add_argument("--cpp-header", type=Path)
    parser.add_argument("--cpp-source", type=Path)
    parser.add_argument("--ts", type=Path)
    args = parser.parse_args()

    try:
        raw = json.loads(args.schema.read_text(encoding="utf-8"))
        schema = Schema(raw)
    except json.JSONDecodeError as error:
        print(f"gen_bridge: {args.schema} is not valid JSON: {error}", file=sys.stderr)
        return 1
    except SchemaError as error:
        print(f"gen_bridge: invalid schema: {error}", file=sys.stderr)
        return 1

    if args.cpp_source and not args.cpp_header:
        print("gen_bridge: --cpp-source needs --cpp-header for the include", file=sys.stderr)
        return 1

    if args.cpp_header:
        write_if_changed(args.cpp_header, emit_cpp_header(schema), "C++ header")
    if args.cpp_source:
        write_if_changed(
            args.cpp_source, emit_cpp_source(schema, args.cpp_header.name), "C++ source"
        )
    if args.ts:
        write_if_changed(args.ts, emit_ts(schema), "TypeScript")

    total = len(schema.methods)
    print(f"gen_bridge: {total} method(s) across {len(schema.capabilities)} capability(ies)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
