#!/usr/bin/env python3
"""Pin a CEF binary distribution into cmake/cef_version.cmake.

Resolves the current stable build from the CEF build index, downloads the
archive once, computes a SHA-256 of what was actually received, and writes a
CMake file that the build then uses verbatim.

Why not let CMake resolve "latest" at configure time: a build whose
dependencies can change under it is not reproducible, and a portfolio project
that cannot be rebuilt in a year is not worth much. Pinning is a commit.

Why SHA-256 and not the published SHA-1: upstream publishes SHA-1 only. SHA-1
is not collision resistant, so this script verifies the SHA-1 it was given and
then records a SHA-256 of the bytes it saw, which is what CMake enforces later.

Usage:
    python tools/pin_cef.py --platforms windows64 macosarm64
    python tools/pin_cef.py --platforms windows64 --channel beta
    python tools/pin_cef.py --platforms windows64 --cef-version 130.1.2+abc123+chromium-130.0.0.0
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import urllib.parse
import urllib.request
from pathlib import Path

INDEX_URL = "https://cef-builds.spotifycdn.com/index.json"
BASE_URL = "https://cef-builds.spotifycdn.com"

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_FILE = REPO_ROOT / "cmake" / "cef_version.cmake"
CACHE_DIR = REPO_ROOT / "third_party" / "cef" / "cache"

CHUNK = 1024 * 1024


def fetch_index() -> dict:
    print(f"fetching {INDEX_URL}")
    with urllib.request.urlopen(INDEX_URL, timeout=120) as response:
        return json.load(response)


def pick_version(index: dict, platform: str, channel: str, wanted: str | None) -> dict:
    if platform not in index:
        raise SystemExit(f"unknown platform '{platform}'. Known: {', '.join(sorted(index))}")

    versions = index[platform].get("versions", [])
    for version in versions:
        if wanted is not None:
            if version.get("cef_version") == wanted:
                return version
            continue
        if version.get("channel") == channel:
            return version

    if wanted is not None:
        raise SystemExit(f"CEF {wanted} is not published for {platform}")
    raise SystemExit(f"no '{channel}' build found for {platform}")


def pick_file(version: dict, distribution: str) -> dict:
    for entry in version.get("files", []):
        if entry.get("type") == distribution:
            return entry
    available = sorted({entry.get("type", "?") for entry in version.get("files", [])})
    raise SystemExit(
        f"no '{distribution}' distribution for CEF {version.get('cef_version')}; "
        f"available: {', '.join(available)}"
    )


def download(file_name: str, destination: Path) -> None:
    url = f"{BASE_URL}/{urllib.parse.quote(file_name, safe='')}"
    destination.parent.mkdir(parents=True, exist_ok=True)
    partial = destination.with_suffix(destination.suffix + ".part")

    print(f"downloading {url}")
    with urllib.request.urlopen(url, timeout=120) as response, partial.open("wb") as out:
        total = int(response.headers.get("Content-Length", 0))
        seen = 0
        while True:
            chunk = response.read(CHUNK)
            if not chunk:
                break
            out.write(chunk)
            seen += len(chunk)
            if total:
                print(f"\r  {seen / 1e6:7.1f} / {total / 1e6:.1f} MB", end="", flush=True)
        print()
    partial.replace(destination)


def digest(path: Path, algorithm: str) -> str:
    hasher = hashlib.new(algorithm)
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(CHUNK), b""):
            hasher.update(chunk)
    return hasher.hexdigest()


def render(cef_version: str, chromium_version: str, distribution: str, pins: dict) -> str:
    lines = [
        "# Generated by tools/pin_cef.py -- do not edit by hand.",
        "#",
        "# Regenerate with:",
        f"#   python tools/pin_cef.py --platforms {' '.join(sorted(pins))}",
        "",
        f'set(CEF_VERSION "{cef_version}")',
        f'set(CEF_CHROMIUM_VERSION "{chromium_version}")',
        f'set(CEF_DISTRIBUTION_TYPE "{distribution}")',
        'set(CEF_BASE_URL "https://cef-builds.spotifycdn.com")',
        "",
    ]
    for platform in sorted(pins):
        pin = pins[platform]
        lines.append(f"# {platform}: {pin['size'] / 1e6:.0f} MB, upstream sha1 {pin['sha1']}")
        lines.append(f'set(CEF_FILE_{platform} "{pin["name"]}")')
        lines.append(f'set(CEF_SHA256_{platform} "{pin["sha256"]}")')
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--platforms", nargs="+", required=True,
                        help="CEF platform keys, e.g. windows64 macosarm64 macosx64")
    parser.add_argument("--channel", default="stable", help="stable or beta (default: stable)")
    parser.add_argument("--cef-version", default=None,
                        help="pin this exact cef_version instead of the newest in the channel")
    parser.add_argument("--distribution", default="minimal",
                        help="minimal, standard, client (default: minimal)")
    parser.add_argument("--keep-archives", action="store_true",
                        help="keep the downloaded archives in third_party/cef/cache")
    args = parser.parse_args()

    index = fetch_index()

    resolved_version: str | None = None
    chromium_version = ""
    pins: dict[str, dict] = {}

    for platform in args.platforms:
        version = pick_version(index, platform, args.channel, args.cef_version)
        cef_version = version["cef_version"]

        # All platforms must land on the same CEF version, otherwise the shell
        # and the UI would be built against different Chromium versions.
        if resolved_version is None:
            resolved_version = cef_version
            chromium_version = version.get("chromium_version", "")
        elif cef_version != resolved_version:
            raise SystemExit(
                f"{platform} resolves to CEF {cef_version} but another platform resolved to "
                f"{resolved_version}. Pass --cef-version to pin one explicitly."
            )

        entry = pick_file(version, args.distribution)
        archive = CACHE_DIR / entry["name"]

        if not archive.exists():
            download(entry["name"], archive)

        actual_sha1 = digest(archive, "sha1")
        if actual_sha1 != entry["sha1"]:
            archive.unlink(missing_ok=True)
            raise SystemExit(
                f"sha1 mismatch for {entry['name']}: index says {entry['sha1']}, "
                f"download is {actual_sha1}"
            )

        pins[platform] = {
            "name": entry["name"],
            "sha1": entry["sha1"],
            "sha256": digest(archive, "sha256"),
            "size": entry.get("size", 0),
        }
        print(f"  {platform}: {entry['name']}")
        print(f"    sha256 {pins[platform]['sha256']}")

        if not args.keep_archives:
            archive.unlink(missing_ok=True)

    assert resolved_version is not None
    OUTPUT_FILE.write_text(
        render(resolved_version, chromium_version, args.distribution, pins),
        encoding="utf-8",
    )
    print(f"\nwrote {OUTPUT_FILE.relative_to(REPO_ROOT)}")
    print(f"CEF {resolved_version} (Chromium {chromium_version})")
    print("Commit this file, then configure with -DSONORA_ENABLE_CEF=ON.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
