# Generated by tools/pin_cef.py -- do not edit by hand.
#
# Regenerate with:
#   python tools/pin_cef.py --platforms macosarm64 windows64

set(CEF_VERSION "152.0.8+g1ce985c+chromium-152.0.7977.134")
set(CEF_CHROMIUM_VERSION "152.0.7977.134")
set(CEF_DISTRIBUTION_TYPE "minimal")
set(CEF_BASE_URL "https://cef-builds.spotifycdn.com")

# macosarm64: 131 MB, upstream sha1 3e989a2f69f7288191e63f19bf303d9256779a94
set(CEF_FILE_macosarm64 "cef_binary_152.0.8+g1ce985c+chromium-152.0.7977.134_macosarm64_minimal.tar.bz2")
set(CEF_SHA256_macosarm64 "3bb9859cb8d3ea60b542023cdd75d10c037fbe21fd544dc6ccb790ad22d1759e")

# windows64: 172 MB, upstream sha1 74289811aa46b242cfbdba7e89f389e70df818b9
set(CEF_FILE_windows64 "cef_binary_152.0.8+g1ce985c+chromium-152.0.7977.134_windows64_minimal.tar.bz2")
set(CEF_SHA256_windows64 "c78fd85d4c604007e199d1abf749bf2ca6d10c1e81d32d22ea0c8f9dfcf7ea92")
