# Generated by tools/pin_cef.py -- do not edit by hand.
#
# Empty on purpose: the CEF build is not pinned yet. Run
#
#   python tools/pin_cef.py --platforms windows64 macosarm64
#
# which resolves the current stable CEF build, downloads it once, and rewrites
# this file with the exact version and a SHA-256 computed locally.

set(CEF_VERSION "")
set(CEF_CHROMIUM_VERSION "")
set(CEF_DISTRIBUTION_TYPE "minimal")
set(CEF_BASE_URL "https://cef-builds.spotifycdn.com")

# One block per platform key: file name and SHA-256 of the archive.
# set(CEF_FILE_windows64 "...")
# set(CEF_SHA256_windows64 "...")
