# Provisions the Chromium Embedded Framework binary distribution.
#
# Not called until SONORA_ENABLE_CEF is ON (week 2), so a week-1 checkout does
# not pay for a ~1 GB download just to build a window.
#
# Design notes worth keeping:
#  * The version and hash live in cmake/cef_version.cmake, generated by
#    tools/pin_cef.py. Nothing here reaches out to discover "the latest" build:
#    a build that silently changes its dependencies is not reproducible.
#  * The archive is verified by SHA-256 before extraction. Upstream publishes
#    SHA-1 only, which is not collision resistant, so pin_cef.py downloads the
#    archive once and records a SHA-256 of what it actually saw.
#  * The download is cached under third_party/cef/cache so a clean build
#    directory does not re-download.

include_guard(GLOBAL)

function(sonora_provision_cef)
  include("${CMAKE_SOURCE_DIR}/cmake/cef_version.cmake")

  if(NOT CEF_VERSION)
    message(FATAL_ERROR
      "CEF is not pinned yet.\n"
      "Run: python tools/pin_cef.py --platforms windows64 macosarm64\n"
      "then commit the regenerated cmake/cef_version.cmake.")
  endif()

  # Map the build host to the platform key used by the CEF build index.
  if(WIN32)
    set(platform_key "windows64")
  elseif(APPLE)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64")
      set(platform_key "macosarm64")
    else()
      set(platform_key "macosx64")
    endif()
  else()
    message(FATAL_ERROR "No CEF platform mapping for this host.")
  endif()

  set(file_name "${CEF_FILE_${platform_key}}")
  set(expected_sha256 "${CEF_SHA256_${platform_key}}")

  if(NOT file_name OR NOT expected_sha256)
    message(FATAL_ERROR
      "CEF is pinned, but not for '${platform_key}'.\n"
      "Run: python tools/pin_cef.py --platforms ${platform_key}")
  endif()

  set(cache_dir "${CMAKE_SOURCE_DIR}/third_party/cef/cache")
  set(extract_dir "${CMAKE_SOURCE_DIR}/third_party/cef/${CEF_VERSION}-${platform_key}")
  set(archive "${cache_dir}/${file_name}")

  if(NOT EXISTS "${extract_dir}/cef_paths.gypi")
    if(NOT EXISTS "${archive}")
      file(MAKE_DIRECTORY "${cache_dir}")
      # The published file names contain '+', which must stay percent-encoded.
      string(REPLACE "+" "%2B" url_file "${file_name}")
      message(STATUS "Downloading CEF ${CEF_VERSION} for ${platform_key} (~1 GB)...")
      file(DOWNLOAD
        "${CEF_BASE_URL}/${url_file}"
        "${archive}"
        EXPECTED_HASH SHA256=${expected_sha256}
        SHOW_PROGRESS
        STATUS download_status
        TLS_VERIFY ON)
      list(GET download_status 0 download_code)
      if(NOT download_code EQUAL 0)
        list(GET download_status 1 download_message)
        file(REMOVE "${archive}")
        message(FATAL_ERROR "CEF download failed: ${download_message}")
      endif()
    endif()

    message(STATUS "Extracting CEF to ${extract_dir}")
    file(MAKE_DIRECTORY "${extract_dir}")
    # The archive has a single top-level directory; strip it so the layout is
    # stable regardless of the version string.
    file(ARCHIVE_EXTRACT
      INPUT "${archive}"
      DESTINATION "${extract_dir}"
      PATTERNS "*"
      VERBOSE OFF)
    file(GLOB extracted_root LIST_DIRECTORIES true "${extract_dir}/cef_binary_*")
    if(extracted_root)
      list(GET extracted_root 0 extracted_root)
      file(GLOB inner_entries "${extracted_root}/*")
      foreach(entry IN LISTS inner_entries)
        get_filename_component(entry_name "${entry}" NAME)
        file(RENAME "${entry}" "${extract_dir}/${entry_name}")
      endforeach()
      file(REMOVE_RECURSE "${extracted_root}")
    endif()
  endif()

  set(CEF_ROOT "${extract_dir}" PARENT_SCOPE)
endfunction()
