# Provisions the Chromium Embedded Framework binary distribution.
#
# Design notes worth keeping:
#  * The version and hash live in cmake/cef_version.cmake, generated by
#    tools/pin_cef.py. Nothing here reaches out to discover "the latest" build:
#    a build that silently changes its dependencies is not reproducible.
#  * The archive is verified by SHA-256 before extraction. Upstream publishes
#    SHA-1 only, which is not collision resistant, so pin_cef.py downloads the
#    archive once and records a SHA-256 of what it actually saw.
#  * The download is cached under third_party/cef/cache so a clean build
#    directory does not re-download a gigabyte.

include_guard(GLOBAL)

function(sonora_provision_cef)
  include("${CMAKE_SOURCE_DIR}/cmake/cef_version.cmake")

  if(NOT CEF_VERSION)
    message(FATAL_ERROR
      "CEF is not pinned yet.\n"
      "Run: python tools/pin_cef.py --platforms windows64 macosarm64\n"
      "then commit the regenerated cmake/cef_version.cmake.")
  endif()

  # Map the build host to the platform key used by the CEF build index.
  if(WIN32)
    set(platform_key "windows64")
  elseif(APPLE)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64")
      set(platform_key "macosarm64")
    else()
      set(platform_key "macosx64")
    endif()
  else()
    message(FATAL_ERROR "No CEF platform mapping for this host.")
  endif()

  set(file_name "${CEF_FILE_${platform_key}}")
  set(expected_sha256 "${CEF_SHA256_${platform_key}}")

  if(NOT file_name OR NOT expected_sha256)
    message(FATAL_ERROR
      "CEF is pinned, but not for '${platform_key}'.\n"
      "Run: python tools/pin_cef.py --platforms ${platform_key}")
  endif()

  set(cache_dir "${CMAKE_SOURCE_DIR}/third_party/cef/cache")
  set(extract_dir "${CMAKE_SOURCE_DIR}/third_party/cef/${CEF_VERSION}-${platform_key}")
  set(archive "${cache_dir}/${file_name}")

  # include/cef_version.h is present in every distribution type and is only in
  # place once the move below has run, so it means a COMPLETE extraction. A
  # partially extracted tree has no marker and is thrown away rather than
  # half-used, which is the failure mode that costs an afternoon.
  #
  # (cef_paths.gypi, the obvious choice, was dropped from CEF distributions
  # when they moved to Bazel. It is not there in 152.)
  if(NOT EXISTS "${extract_dir}/include/cef_version.h")
    if(EXISTS "${extract_dir}")
      message(STATUS "Removing an incomplete CEF extraction at ${extract_dir}")
      file(REMOVE_RECURSE "${extract_dir}")
    endif()

    if(NOT EXISTS "${archive}")
      file(MAKE_DIRECTORY "${cache_dir}")
      # The published file names contain '+', which must stay percent-encoded.
      string(REPLACE "+" "%2B" url_file "${file_name}")
      message(STATUS "Downloading CEF ${CEF_VERSION} for ${platform_key} (~1 GB)...")
      file(DOWNLOAD
        "${CEF_BASE_URL}/${url_file}"
        "${archive}"
        EXPECTED_HASH SHA256=${expected_sha256}
        SHOW_PROGRESS
        STATUS download_status
        TLS_VERIFY ON)
      list(GET download_status 0 download_code)
      if(NOT download_code EQUAL 0)
        list(GET download_status 1 download_message)
        file(REMOVE "${archive}")
        message(FATAL_ERROR "CEF download failed: ${download_message}")
      endif()
    endif()

    message(STATUS "Extracting CEF (this takes a minute)...")
    set(staging_dir "${extract_dir}.staging")
    file(REMOVE_RECURSE "${staging_dir}")
    file(MAKE_DIRECTORY "${staging_dir}")

    # No PATTERNS and no VERBOSE: both are bare flags in file(ARCHIVE_EXTRACT),
    # so passing a value after VERBOSE is an "Unrecognized argument" error.
    file(ARCHIVE_EXTRACT
      INPUT "${archive}"
      DESTINATION "${staging_dir}")

    # The archive contains a single top-level cef_binary_<version> directory.
    # Stripping it keeps the layout stable no matter what the version string is.
    file(GLOB extracted_roots LIST_DIRECTORIES true "${staging_dir}/cef_binary_*")
    list(LENGTH extracted_roots root_count)
    if(NOT root_count EQUAL 1)
      file(REMOVE_RECURSE "${staging_dir}")
      message(FATAL_ERROR
        "Expected exactly one cef_binary_* directory in the archive, found ${root_count}.")
    endif()
    list(GET extracted_roots 0 extracted_root)

    file(RENAME "${extracted_root}" "${extract_dir}")
    file(REMOVE_RECURSE "${staging_dir}")

    if(NOT EXISTS "${extract_dir}/include/cef_version.h")
      message(FATAL_ERROR "CEF extracted, but ${extract_dir}/include/cef_version.h is missing.")
    endif()
    message(STATUS "CEF ready at ${extract_dir}")
  endif()

  set(CEF_ROOT "${extract_dir}" PARENT_SCOPE)
endfunction()
