# Generates the C++ half of the bridge from schema/bridge.schema.json.
#
# The TypeScript half is generated by npm (see ui/package.json), not here. Two
# build systems writing the same file race each other, so each generated
# artifact has exactly one owner.

include_guard(GLOBAL)

find_package(Python3 REQUIRED COMPONENTS Interpreter)

function(sonora_generate_bridge header_var source_var)
  set(generated_dir "${CMAKE_CURRENT_BINARY_DIR}/generated")
  set(header "${generated_dir}/bridge_generated.h")
  set(source "${generated_dir}/bridge_generated.cpp")
  set(schema "${CMAKE_SOURCE_DIR}/schema/bridge.schema.json")
  set(script "${CMAKE_SOURCE_DIR}/tools/gen_bridge.py")

  # Runs at build time, not configure time, so editing the schema and
  # rebuilding is enough -- no re-running CMake. The generator rewrites its
  # outputs only when the content actually changes, so an unchanged schema does
  # not drag the whole shell through a rebuild.
  add_custom_command(
    OUTPUT "${header}" "${source}"
    COMMAND "${Python3_EXECUTABLE}" "${script}"
            --schema "${schema}"
            --cpp-header "${header}"
            --cpp-source "${source}"
    DEPENDS "${script}" "${schema}"
    COMMENT "Generating the bridge from schema/bridge.schema.json"
    VERBATIM)

  set(${header_var} "${header}" PARENT_SCOPE)
  set(${source_var} "${source}" PARENT_SCOPE)
endfunction()
